In [3]:
# import dependencies
import zipfile
import pandas as pd
import os

In [13]:
Sep2013_df = pd.read_csv('data/201309-citibike-tripdata.zip', compression='zip')
Sep2013_df.head(20)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1010,2013-09-01 00:00:02,2013-09-01 00:16:52,254,W 11 St & 6 Ave,40.735324,-73.998004,147,Greenwich St & Warren St,40.715422,-74.011220,15014,Subscriber,1974,1
1,1443,2013-09-01 00:00:09,2013-09-01 00:24:12,151,Cleveland Pl & Spring St,40.721816,-73.997203,497,E 17 St & Broadway,40.737050,-73.990093,19393,Customer,\N,0
2,1387,2013-09-01 00:00:16,2013-09-01 00:23:23,352,W 56 St & 6 Ave,40.763406,-73.977225,405,Washington St & Gansevoort St,40.739323,-74.008119,16160,Subscriber,1992,1
3,405,2013-09-01 00:00:18,2013-09-01 00:07:03,490,8 Ave & W 33 St,40.751551,-73.993934,459,W 20 St & 11 Ave,40.746745,-74.007756,14997,Subscriber,1973,1
4,270,2013-09-01 00:00:20,2013-09-01 00:04:50,236,St Marks Pl & 2 Ave,40.728419,-73.987140,393,E 5 St & Avenue C,40.722992,-73.979955,19609,Subscriber,1984,1
5,400,2013-09-01 00:00:35,2013-09-01 00:07:15,490,8 Ave & W 33 St,40.751551,-73.993934,453,W 22 St & 8 Ave,40.744751,-73.999154,17523,Subscriber,1978,1
6,115,2013-09-01 00:00:47,2013-09-01 00:02:42,351,Front St & Maiden Ln,40.705310,-74.006126,351,Front St & Maiden Ln,40.705310,-74.006126,19533,Customer,\N,0
7,1080,2013-09-01 00:00:48,2013-09-01 00:18:48,2000,Front St & Washington St,40.702551,-73.989402,418,Front St & Gold St,40.702240,-73.982578,18487,Subscriber,1972,2
8,2550,2013-09-01 00:00:49,2013-09-01 00:43:19,533,Broadway & W 39 St,40.752996,-73.987216,2021,W 45 St & 8 Ave,40.759291,-73.988597,19342,Subscriber,1949,1
9,1108,2013-09-01 00:00:49,2013-09-01 00:19:17,301,E 2 St & Avenue B,40.722174,-73.983688,306,Cliff St & Fulton St,40.708235,-74.005301,15177,Subscriber,1978,1
10,413,2013-09-01 00:01:01,2013-09-01 00:07:54,421,Clermont Ave & Park Ave,40.695734,-73.971297,399,Lafayette Ave & St James Pl,40.688515,-73.964763,15809,Subscriber,1987,1
11,1099,2013-09-01 00:01:06,2013-09-01 00:19:25,249,Harrison St & Hudson St,40.718710,-74.009001,489,10 Ave & W 28 St,40.750664,-74.001768,14588,Subscriber,1979,1
12,1626,2013-09-01 00:01:11,2013-09-01 00:28:17,2002,Wythe Ave & Metropolitan Ave,40.716887,-73.963198,401,Allen St & Rivington St,40.720196,-73.989978,19490,Subscriber,1968,1
13,1562,2013-09-01 00:01:12,2013-09-01 00:27:14,415,Pearl St & Hanover Square,40.704718,-74.009260,501,FDR Drive & E 35 St,40.744219,-73.971212,14886,Subscriber,1992,1
14,954,2013-09-01 00:01:14,2013-09-01 00:17:08,466,W 25 St & 6 Ave,40.743954,-73.991449,339,Avenue D & E 12 St,40.725806,-73.974225,18040,Subscriber,1977,1
15,255,2013-09-01 00:01:15,2013-09-01 00:05:30,494,W 26 St & 8 Ave,40.747348,-73.997236,509,9 Ave & W 22 St,40.745497,-74.001971,15025,Subscriber,1982,2
16,796,2013-09-01 00:01:22,2013-09-01 00:14:38,494,W 26 St & 8 Ave,40.747348,-73.997236,127,Barrow St & Hudson St,40.731724,-74.006744,16567,Subscriber,1968,2
17,163,2013-09-01 00:01:29,2013-09-01 00:04:12,384,Fulton St & Waverly Ave,40.683178,-73.965964,365,Fulton St & Grand Ave,40.682232,-73.961458,15106,Subscriber,1982,1
18,1233,2013-09-01 00:01:32,2013-09-01 00:22:05,457,Broadway & W 58 St,40.766953,-73.981693,254,W 11 St & 6 Ave,40.735324,-73.998004,17024,Subscriber,1976,1
19,1313,2013-09-01 00:01:33,2013-09-01 00:23:26,290,2 Ave & E 58 St,40.760203,-73.964785,473,Rivington St & Chrystie St,40.721101,-73.991925,20337,Customer,\N,0

In [22]:
Aug2021_df = pd.read_csv('data/JC-202108-citibike-tripdata.csv')
Aug2021_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,5CABAE380FF3C7E0,classic_bike,2021-08-06 07:02:02,2021-08-06 07:28:56,Dey St,JC065,Stevens - River Ter & 6 St,HB602,40.737711,-74.066921,40.743133,-74.026989,casual
1,0C820F4E9256B5BB,classic_bike,2021-08-15 19:48:51,2021-08-15 20:04:45,Grand St & 2 St,HB405,Jersey & 3rd,JC074,40.739130,-74.036180,40.723332,-74.045953,member
2,F33B1B767F55A2BC,classic_bike,2021-08-26 17:14:58,2021-08-26 17:20:13,Grand St & 2 St,HB405,7 St & Monroe St,HB304,40.739130,-74.036180,40.746413,-74.037977,casual
3,EF7A1541C2302EEF,classic_bike,2021-08-12 12:58:22,2021-08-12 13:04:07,Dey St,JC065,Sip Ave,JC056,40.737711,-74.066921,40.730897,-74.063913,member
4,74DEC24E4C66BA01,classic_bike,2021-08-04 20:59:45,2021-08-04 21:10:39,Glenwood Ave,JC094,Pershing Field,JC024,40.727551,-74.071061,40.742677,-74.051789,member

In [21]:
Aug2021_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,5CABAE380FF3C7E0,classic_bike,2021-08-06 07:02:02,2021-08-06 07:28:56,Dey St,JC065,Stevens - River Ter & 6 St,HB602,40.737711,-74.066921,40.743133,-74.026989,casual
1,0C820F4E9256B5BB,classic_bike,2021-08-15 19:48:51,2021-08-15 20:04:45,Grand St & 2 St,HB405,Jersey & 3rd,JC074,40.739130,-74.036180,40.723332,-74.045953,member
2,F33B1B767F55A2BC,classic_bike,2021-08-26 17:14:58,2021-08-26 17:20:13,Grand St & 2 St,HB405,7 St & Monroe St,HB304,40.739130,-74.036180,40.746413,-74.037977,casual
3,EF7A1541C2302EEF,classic_bike,2021-08-12 12:58:22,2021-08-12 13:04:07,Dey St,JC065,Sip Ave,JC056,40.737711,-74.066921,40.730897,-74.063913,member
4,74DEC24E4C66BA01,classic_bike,2021-08-04 20:59:45,2021-08-04 21:10:39,Glenwood Ave,JC094,Pershing Field,JC024,40.727551,-74.071061,40.742677,-74.051789,member

## old vs new
#### starttime = started_at
#### stoptime = ended_at
#### start station id = start_station_id // start station name = start_station_name // start station latitude = start_lat // start station longitude = start_lng
#### end station id = end_station_id // end station name = end_station_name // end station latitude = end_lat // end station longitude = end_lng
#### usertype = member_casual

## Possible questions
* does duration of ride vary between casual users & members? (need to calculate duration)
* do certain stations have more casual users than members?
* have ridership patterns changed over the years? (need to compare same month(s) for multiple years)
* how do ridership patterns vary over the seasons/months? (need to look at months; possibly calculate seasons)
* does speed of travel vary between casual riders & members? (need to calculate based on duration vs distance--which would need to be calculated via coordinates)
* does the type of rider vary by time of day? 
* does duration vary by time of day?
* are certain stations associated with longer rides?

## Possible data transformations
* does time need to be converted in any way?

## Very Basic Questions to answer before making further decisions

In [18]:
# How many unique start stations are there?
start_stations = Aug2021_df['start_station_id'].nunique()
start_stations

76

In [29]:
# What are the starting stations?
start_station_list = Aug2021_df['start_station_id'].unique()
start_station_list

array(['JC065', 'HB405', 'JC094', 'JC066', 'JC106', 'JC024', 'HB103',
       'JC055', 'HB302', 'JC074', 'HB304', 'JC072', 'JC059', 'JC005',
       'HB303', 'HB505', 'JC078', 'JC011', 'JC077', 'JC052', 'HB202',
       'JC102', 'JC038', 'JC009', 'JC014', 'JC103', 'JC095', 'HB503',
       'JC006', 'JC019', 'JC104', 'JC027', 'JC002', 'JC063', 'JC099',
       'JC023', 'JC057', 'HB601', 'JC075', 'HB502', 'JC098', 'HB401',
       'HB305', 'HB404', 'HB201', 'HB402', 'HB602', 'HB603', 'JC108',
       'JC003', 'HB102', 'JC053', 'JC051', 'JC056', 'JC081', 'JC082',
       'JC018', 'HB203', 'JC076', 'HB501', 'JC013', 'JCSYS', 'JC022',
       'HB101', 'HB507', 'JC008', 'HB301', 'JC035', 'JC032', 'JC084',
       'JC020', 'JC107', 'JC105', 'HB506', 'JC080', 'JC034'], dtype=object)

In [39]:
# How many bikes left from each station?
start_numbers = Aug2021_df['start_station_id'].value_counts()
start_numbers

pandas.core.series.Series

In [20]:
# How many unique end stations are there?
end_stations = Aug2021_df['end_station_id'].nunique()
end_stations

111

In [30]:
# What are the ending stations?
end_station_list = Aug2021_df['end_station_id'].unique()
end_station_list

array(['HB602', 'JC074', 'HB304', 'JC056', 'JC024', 'JC094', 'HB402',
       'JC053', 'HB102', nan, 'JC072', 'JC019', 'JC051', 'JC078', 'JC011',
       '8358.10', 'JC084', 'JC009', 'HB305', 'HB103', 'JC065', 'JC035',
       'JC108', 'HB507', 'JC032', 'JC059', 'JC082', 'HB601', 'JC022',
       'JC027', 'JC006', 'JC008', 'JC013', 'HB405', 'JC052', 'HB505',
       'JC002', 'HB503', 'JC104', 'HB501', 'JC103', 'JC098', 'HB302',
       'HB203', '4659.02', 'JC003', 'JC018', 'JC020', 'HB404', 'HB101',
       'JC075', 'JC005', '4565.04', 'JC081', 'HB603', 'JC102', 'JC023',
       'HB201', '8399.06', '5190.09', '6450.12', 'JC106', 'HB303',
       'JC076', 'JC095', 'JC107', '5065.04', '4953.04', 'HB301', 'HB202',
       '8123.02', 'JC099', '5721.14', 'JC038', 'JC014', 'HB502', 'JC077',
       'JC057', 'HB401', '5400.05', '8210.01', 'JC066', 'JCSYS',
       '5297.02', 'JC063', '6765.01', '5880.02', 'JC105', 'JC055',
       '7288.04', '7059.08', '5470.10', '6157.04', '5730.08', '5145.02',
       '4993.02', '5763.03', '7680.03', '4199.12', '6676.02', '6022.04',
       '5644.05', '6364.07', '5329.03', '5636.11', '7059.01', 'HB506',
       '6039.06', '3253.01', '6425.04', 'JC080', 'JC034'], dtype=object)

In [40]:
# How many bikes returned to each station?
end_numbers = Aug2021_df['end_station_id'].value_counts()
end_numbers

HB103      4606
HB101      3933
JC005      3868
HB102      3270
JC008      3111
           ...
6022.04       1
5145.02       1
8210.01       1
5721.14       1
7680.03       1
Name: end_station_id, Length: 111, dtype: int64

In [41]:
# End station names (trying to determine if there is a catchall name if bikes aren't returned to a station)
end_names = Aug2021_df['end_station_name'].value_counts()
end_names

South Waterfront Walkway - Sinatra Dr & 1 St    4606
Hoboken Terminal - Hudson St & Hudson Pl        3933
Grove St PATH                                   3868
Hoboken Terminal - River St & Hudson Pl         3270
Newport Pkwy                                    3111
                                                ...
Myrtle Ave & St Edwards St                         1
Cathedral Pkwy & Broadway                          1
Great Jones St                                     1
Fort Washington Ave & W 183 St                     1
Albany St & Greenwich St                           1
Name: end_station_name, Length: 111, dtype: int64

In [32]:
# How many casual users vs members?
user_types = Aug2021_df['member_casual'].value_counts()
user_types

casual    52769
member    41031
Name: member_casual, dtype: int64

In [34]:
# Is anything _other_than_ "classic_bike" used?
bike_types = Aug2021_df['rideable_type'].value_counts()
bike_types

classic_bike    92286
docked_bike      1514
Name: rideable_type, dtype: int64